export const LOAD_FIREBASE_USER="LOAD_FIREBASE_USER";
export const LOAD_TAKITRI_USER="LOAD_TAKITRI_USER";
export const IS_AUTENTICATED="IS_AUTENTICATED";

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const SHOW_INFORMATION_SONG = 'SHOW_INFORMATION_SONG';

export const UPDATE_IS_FIRSTTIME = 'UPDATE_IS_FIRSTTIME';
