export const HOME_PAGE_USER="HOME_PAGE_USER";
export const PLAY_MUSIC_HOME="PLAY_MUSIC_HOME";
export const LOAD_CURRENT_MUSIC="LOAD_CURRENT_MUSIC";
export const LOAD_AUDIO_PLAYER="LOAD_AUDIO_PLAYER";
export const IS_PLAYING_SOUND="IS_PLAYING_SOUND";
export const LOAD_CURRENT_PLAYLIST="LOAD_CURRENT_PLAYLIST";
