export const HOME_PAGE_USER="HOME_PAGE_USER";
export const PLAY_MUSIC_HOME="PLAY_MUSIC_HOME";
export const LOAD_CURRENT_MUSIC="LOAD_CURRENT_MUSIC";
export const LOAD_AUDIO_PLAYER="LOAD_AUDIO_PLAYER";
export const IS_PLAYING_SOUND="IS_PLAYING_SOUND";
export const LOAD_CURRENT_PLAYLIST="LOAD_CURRENT_PLAYLIST";

export const LOAD_ISLIKE_SONG="LOAD_ISLIKE_SONG";
export const IS_ON_LONG_PRESS="IS_ON_LONG_PRESS";
export const PUSH_SELECTED_ITEM_LIST="PUSH_SELECTED_ITEM_LIST";
export const DELETE_SELECTED_ITEM_LIST="DELETE_SELECTED_ITEM_LIST";

export const IS_LOADING_PAGE="IS_LOADING_PAGE";
export const IS_MODAL_ERROR_VISIBLE_PAGE="IS_MODAL_ERROR_VISIBLE_PAGE";
export const MESSAGE_ERROR_MODAL="MESSAGE_ERROR_MODAL";

